load(
    "//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", 
    "mediapipe_aar"
)

mediapipe_aar(
    name = "ar_image_tracking",
    calculators = ["//mediapipe/graphs/ar_image_tracking:mobile_calculators"],
)

# mediapipe_aar(
#     name = "depth_detection",
#     calculators = ["//mediapipe/graphs/ar_image_tracking:depth_detection_calculators"],
# )